receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      load:
      memory:
      network:
      paging:
      processes:
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true
        mute_process_cgroup_error: true
        metrics:
          process.cpu.utilization:
            enabled: true
          process.memory.utilization:
            enabled: true
  hostmetrics/disk:
    collection_interval: 1m
    scrapers:
      disk:
      filesystem:

processors:
  batch: {}

exporters:
  otlp:
    endpoint: https://192.168.122.1:4318 # <- switched to gRPC port (4317)
    tls:
      cert_file: /etc/flightctl/certs/otel.crt
      key_file: /etc/flightctl/certs/otel.key
      ca_file: /etc/flightctl/certs/ca.crt
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, hostmetrics/disk]
      processors: [batch]
      exporters: [debug, otlp]
